#!/usr/bin/env bash

set -o errexit

REPO_URL=https://github.com/baxterjo/.dotfiles.git
REPO_PATH="$HOME/.dotfiles"

if [ -z "${REPO_BRANCH+x}" ]; then
  REPO_BRANCH=main
fi

reset_color=$(tput sgr 0)

info() {
  printf "%s[*] %s%s\n" "$(tput setaf 4)" "$1" "$reset_color"
}

success() {
  printf "%s[*] %s%s\n" "$(tput setaf 2)" "$1" "$reset_color"
}

err() {
  printf "%s[*] %s%s\n" "$(tput setaf 1)" "$1" "$reset_color"
}

warn() {
  printf "%s[*] %s%s\n" "$(tput setaf 3)" "$1" "$reset_color"
}

install_xcode() {
  if xcode-select -p >/dev/null; then
    warn "xCode Command Line Tools already installed"
  else
    info "Installing xCode Command Line Tools..."
    xcode-select --install
    sudo xcodebuild -license accept
  fi
}

install_homebrew() {
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  if ! command -v brew &>/dev/null; then
    info "Installing homebrew..."
    sudo --validate # reset `sudo` timeout to use Homebrew install in noninteractive mode
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  else
    warn "Homebrew already installed"
  fi
}

bootstrap_mac() {
  install_xcode
  install_homebrew

  info "Installing Git"
  brew install git
}

bootstrap_linux() {
  sudo apt-get install -y build-essential procps curl file git
  install_homebrew

  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.bashrc
}

bootstrap() {
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Source some vars from the OS installation
    . /etc/os-release

    # Linux installation requires apt.
    if [[ "$ID_LIKE" != "debian" ]]; then
      err "${ID_LIKE} is not a supported linux distro"
      exit 1
    fi
    bootstrap_linux
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    bootstrap_mac
  else
    err "${OSTYPE} not supported."
    exit 1
  fi
}

main() {
  info "########################"
  info "####### dotfiles #######"
  info "########################"
  # If in interactive mode, wait for input.
  if [ -t 0 ]; then
    read -r -p "Press enter to start:"
  fi
  info "Bootstraping..."
  bootstrap

  # Clone repo only if it doesn't already exist with the same remote
  if [ -d "$REPO_PATH/.git" ]; then
    existing_remote=$(git -C "$REPO_PATH" config --get remote.origin.url 2>/dev/null)
    if [ "$existing_remote" == "$REPO_URL" ]; then
      info ".dotfiles repository already exists at ${REPO_PATH}, checking out branch."
      git -C "$REPO_PATH" checkout "$REPO_BRANCH"
      git pull
    else
      err "Repository already exists at $REPO_PATH and does not have the same origin!"
      err "local_origin : $existing_remote, desired_origin: $REPO_URL"
      exit 1
    fi
  else
    info "Cloning .dotfiles repo from $REPO_URL at $REPO_BRANCH into $REPO_PATH"
    git clone -b "$REPO_BRANCH" "$REPO_URL" "$REPO_PATH"
  fi

  info "Change path to $REPO_PATH"
  cd "$REPO_PATH" >/dev/null

  /bin/bash ./install.sh
}

# If an argument is given to this script, assume it is a function call.
if [ -n "${1:-}" ]; then
  $1
# Bash equivalent to `if __name__ == "__main__"` in python
# Also handles piped execution (curl ... | bash)
elif [ "${BASH_SOURCE[0]}" = "$0" ] || [ "$0" = "bash" ] || [ "$0" = "-bash" ]; then
  main
fi
