[env]
CC_wasm32_unknown_unknown = "/opt/homebrew/opt/llvm/bin/clang"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[net]
git-fetch-with-cli = true
