"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$docker_context\
$c\
$cmake\
$deno\
$elixir\
$golang\
$lua\
$nodejs\
$python\
$rust\
$zig\
$package\
$line_break\
$character"""

right_format = """
$cmd_duration\
$jobs\
$status"""

[status]
disabled = false

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "[ $duration]($style) "

[directory]
truncate_to_repo = false
truncation_length = 3
format = "[$path]($style)[$repo_root]($repo_root_style)[$read_only]($read_only_style) "
read_only = " "

[c]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "
style = "bold fg:#f07178"

[golang]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
