"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character"""

right_format = """
$cmd_duration\
$jobs\
$status\
$kubernetes\
$docker_context\
$c\
$cmake\
$deno\
$elixir\
$golang\
$lua\
$nodejs\
$python\
$rust\
$zig"""

[memory_usage]
disabled = false
symbol = ""
threshold = 30
format = "[$symbol ${ram}]($style)"

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count} "
behind = "⇣${count} "
ahead = "⇡${count} "
modified = "!${count} "
untracked = "?${count} "
stashed = "$${count} "
staged = "+${count} "
deleted = "x${count} "
renamed = "»${count} "

[status]
disabled = false

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "[ $duration]($style) "

[directory]
truncate_to_repo = false
truncation_length = 1
format = "[$path]($style)[$repo_root]($repo_root_style)[$read_only]($read_only_style) "
read_only = " "

[c]
format = "[$symbol($version(-$name) )]($style)"
symbol = " "

[docker_context]
format = "[$symbol$context]($style)"
symbol = " "

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'
symbol = " "

[git_branch]
symbol = " "
style = "bold fg:#f07178"

[golang]
format = "[$symbol($version)]($style)"
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[package]
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = " "
