matches:
  - trigger: ":build-date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y%m%d%H%M"

  - trigger: ":ip-add"
    replace: "{{ip}}"
    vars:
      - name: ip
        type: shell
        params:
          cmd: "ifconfig en0| grep \"inet[ ]\" | awk '{print $2}'"

  - trigger: ":mdlink"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ":mit"
    replace: "Licensed under MIT X11, © Brian Mayo {{year}}: https://protiumx.dev"
    vars: [{name: year, type: date, params: {format: "%Y"}}]

  - regex: ":cht<(?P<command>.*)>"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'curl "https://cht.sh/{{command}}?QT&style=bw"'
