theme = "onedark"

[editor]
mouse = false

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.insert]
C-c = "normal_mode"

[keys.select]
"C-/" = "toggle_comments"

[keys.normal]
";" = "command_mode"
"`" = { "`" = "goto_previous_buffer" }
":" = { ":" = ":buffer-close" }

